### ISSUE TITLE
ifndef with else results in bad version construct

### ISSUE THREAD

**Issue by schveiguy** [dkorpel/ctod#10]
C:
```c
#ifndef foo
   int x;
#else
   long x;
#endif
```
D:
```d
version (foo) {} else {
   int x;
} else {
   c_long x;
}
```

What needs to happen, unfortunately, is the else branch needs to be copied into the first brace set. Not sure if this is easy to do.

**Comment by schveiguy** [comment]
Or the HasVersion trick has to be used with `!`

**Comment by dkorpel** [comment]
Fixed by https://github.com/dkorpel/ctod/commit/8495b2a9c12b7267ed7da7c39bacb0dd334bacbe
