### ISSUE TITLE
offsetof should be translated

### ISSUE THREAD

**Issue by schveiguy** [dkorpel/ctod#11]
C has a defined macro `offsetof` [documented here](https://en.cppreference.com/w/cpp/types/offsetof)

This should be translated to D's `offsetof` property.

**Comment by dkorpel** [comment]
Fixed by https://github.com/dkorpel/ctod/commit/2757609946daa9f1b9277485bd85d521007acd38

Though only the simplest form with two identifiers, not extensions such as `offsetof(struct Foo { int a; }, a)`.
