### ISSUE TITLE
Distinguish struct / array initializers

### ISSUE THREAD

**Issue by dkorpel** [dkorpel/ctod#12]
C:
```C
int x[3] = {10, 20};

typedef struct {
    int x;
    int y;
} S;

S y = {10, 20};
```

D:
```D
int[3] x = [10, 20];

struct _S {
    int x;
    int y;
}alias _S S;

S y = [10, 20];
```

The struct initializer should not use [] brackets.

**Comment by schveiguy** [comment]
In translating raygui, this has been the most manual part of the process. The ` = {...}` syntax is used all over the place.

**Comment by schveiguy** [comment]
Something else that happens as well, C literals for structs are e.g.:

```c
(Rectangle){x, y, width, height}
```

Which don't translate to D well:

```d
Rectangle x = (Rectangle)[1, 2, 3, 4];
```

Using `{}` won't work in D, it has to be:
```d
Rectangle x = Rectangle(1, 2, 3, 4);
```
I had a lot of these to translate.

**Comment by dkorpel** [comment]
As of https://github.com/dkorpel/ctod/commit/66b4c4303e7292e175d0a7958ec6d8606dba929d there's basic translation of compound literals, though it won't work when it has designators since D has no named arguments yet.

**Comment by schveiguy** [comment]
At least the code I'm working with, there's no usage of named members.

**Comment by dkorpel** [comment]
Fixed by https://github.com/dkorpel/ctod/commit/e8eec4225aa87e13c08cbcb7bb37b3f8287f9e14
