### ISSUE TITLE
Struct members that are floating point or char should be default initialized to zero

### ISSUE THREAD

**Issue by schveiguy** [dkorpel/ctod#15]
Based on https://github.com/dkorpel/ctod/issues/8#issuecomment-1277268463 (so it's not lost)

Most C code that initializes C structs does so via `= {0}` which has no D equivalent.

Alternatively, assigning `{0}` could be replaced with some template that zeroes everything. But likely this is not required for most C code.

**Comment by dkorpel** [comment]
Fixed by https://github.com/dkorpel/ctod/commit/676826c1571ed189a7917abf4a9d9026c534a8b6
