### ISSUE TITLE
C code seems to have degenerate parsing time for some construct

### ISSUE THREAD

**Issue by SamAxe** [dkorpel/ctod#17]
I was playing with transforming neomutt/nntp source code and it seemed to hang.  I didn't hone in on the exact construct that is causing the parsing issue. :/

The attached `newsrc.txt` file is a slightly reduced version.  This is about 100 lines and takes 20s to translate.  Delete a few lines and it goes to 9 seconds and the right lines and it's under 1 sec.  I'm not sure if this is still a valid reproduce case as I've deleted enough arbitrarily that it likely isn't valid C anymore either.

[newsrc.txt](https://github.com/dkorpel/ctod/files/9802806/newsrc.txt)

**Comment by dkorpel** [comment]
Looks like you're running into the same thing as: https://github.com/dkorpel/ctod/issues/16

After the fix, your file takes 140ms to translate for me. Please update to v1.0.1! This bug is embarrassing.

**Comment by SamAxe** [comment]
Confirmed that 1.0.1 fixes it.  Thank you very much!

**Comment by jordan4ibanez** [comment]
No need to be embarrassed! Everyone makes mistakes. It is simply incredible that this utility allows this to be done so easily
