### ISSUE TITLE
lib-tree-sitter-src/makefile is empty

### ISSUE THREAD

**Issue by schveiguy** [dkorpel/ctod#18]
Not sure if this was intentional. In order to build on macos, I used the build from the original tree-sitter source, so I don't technically need this to build. But I did expect it to actually work with an apparent makefile, only to find it's empty.

**Comment by schveiguy** [comment]
Oh wait, the makefile is empty on purpose. It's not used, but probably it should be removed.

**Comment by dkorpel** [comment]
You can build the included sources with the makefile in the root, the empty file is a relic. I deleted the file in https://github.com/dkorpel/ctod/commit/fe97e5bc69494ebaa22ae5e1741880e8bfb4fc3e
