### ISSUE TITLE
What to do with linkage definitions?

### ISSUE THREAD

**Issue by schveiguy** [dkorpel/ctod#19]
In a file I'm translating, I have this (this is common for Windows systems):

```c
// Function specifiers in case library is build/used as a shared library (Windows)
// NOTE: Microsoft specifiers to tell compiler that symbols are imported/exported from a .dll
#if defined(_WIN32)
    #if defined(BUILD_LIBTYPE_SHARED)
        #define RAYGUIAPI __declspec(dllexport)     // We are building the library as a Win32 shared library (.dll)
    #elif defined(USE_LIBTYPE_SHARED)
        #define RAYGUIAPI __declspec(dllimport)     // We are using the library as a Win32 shared library (.dll)
    #endif
#endif

// Function specifiers definition
#ifndef RAYGUIAPI
    #define RAYGUIAPI       // Functions defined as 'extern' by default (implicit specifiers)
#endif
```

Then things are defined like:

```c
RAYGUIAPI void GuiEnable(void);
```

But when passed via ctod it comes out like:

```d
RAYGUIAPI GuiEnable();
```
Which somehow swallows the return type. I can work around by just removing all the RAYGUIAPI in all cases, but this seems like something that might need addressing.

No rush of course on this, I'm not building DLLs here.

Some possible thoughts -- I don't see how you can correctly translate this to D, as it doesn't allow such a string replacement as the C preprocessor allows. But, what if you could just define direct string replacements? Like, just say, `ctod --redefine RAYGUIAPI=export` or `ctod --redefine RAYGUIAPI=`?

**Comment by dkorpel** [comment]
I had this issue with GLFW as well, which also uses macros to specify linkage. This is another one that requires manual pre-processing like https://github.com/dkorpel/ctod/issues/2

**Comment by schveiguy** [comment]
So i have been working on a tool, here: https://github.com/schveiguy/cpptool

The goal of this tool is to replace the macro usages with their definitions, but still leave the #include and other stuff intact for ctod to translate.

So far, it's working OK.

But this is how I'm solving some of these trickier C preprocessor usages.

**Comment by dkorpel** [comment]
Nice!

**Comment by dkorpel** [comment]
As of https://github.com/dkorpel/ctod/commit/7767f699cc816b9158745a00d3afcdd6fcb6f1d8, the return type is no longer swallowed by the API macro. Since I don't want to silently remove the API macro, I just leave it there in the D translation so dmd will raise an error about it.
