### ISSUE TITLE
ifndef with definition

### ISSUE THREAD

**Issue by schveiguy** [dkorpel/ctod#20]
```c
#ifndef foo
  #define foo bar
#endif
```
```d
version (foo) {} else {
  enum foo = bar;
}
```
Somewhat nonsensical. Though I get how this happens. Just bringing it up in case there's any better way to handle this.

**Comment by dkorpel** [comment]
Fixed by https://github.com/dkorpel/ctod/commit/5e3cf6180023889051d7adff08855d3b00d1f829
