### ISSUE TITLE
for loop with multiple variables with different types doesn't translate well.

### ISSUE THREAD

**Issue by schveiguy** [dkorpel/ctod#21]
```c
    for(int i = 1, j = 2; i < 5; ++i) {
    }
```
```d
    for(int i = 1;int j = 2; i < 5; ++i) {
    }
```

**Comment by dkorpel** [comment]
The original case is fixed by https://github.com/dkorpel/ctod/commit/58a9e1a5811c62ce3451d19e7a3cda2fee50624d since both variables have the same type.

The mixed type example I posted still fails though.

**Comment by schveiguy** [comment]
Yeah, the pointer/int combo might be something that is so rare that maybe isn't worth fretting over.

**Comment by schveiguy** [comment]
One thing nice to have probably is a list of things that do not translate well, and how to deal with them.

**Comment by dkorpel** [comment]
> In D you have to put one of them outside the for loop.

Totally forgot about block statements being allowed as for-loop initializer, fixed now
