### ISSUE TITLE
`typedef enum { ... } E;` should provide aliases for values

### ISSUE THREAD

**Issue by schveiguy** [dkorpel/ctod#22]
In C, when you define an enum type, the members are accessible without the namespace.

This needs to be reproduced in D for equivalent code to compile.

e.g.:

```c
enum X
{
    A,
    B
};

int x = A;
```

current conversion:

```d
enum X
{
    A,
    B
}

int x = A;
```

Proposed conversion:

```d
enum X
{
    A,
    B
}
alias A = X.A;
alias B = X.B;

int x = A;
```

**Comment by schveiguy** [comment]
FYI, I used this implementation in raygui: https://github.com/schveiguy/raylib-d/blob/be80478006812a6bd642b6575fe11041898736d7/source/raygui.d#L3-L12

However, it may not work for betterC projects, due to the requirement to use the GC for runtime.

**Comment by schveiguy** [comment]
This didn't work for me.

The case that doesn't seem to work is:

```c
typedef enum { a, b, c } Foo;
```
```d
enum _Foo { a, b, c }; alias Foo = _Foo;
```

No aliases to the members. If I add a tag to the enum, it works.

**Comment by dkorpel** [comment]
Oh right, my test case with `typedef` still gives a name to the `enum`, but that is a case where the anonymous enum still needs to write out aliases.

**Comment by dkorpel** [comment]
Fixed by https://github.com/dkorpel/ctod/commit/736ceb5824b68ddee730bce4e53180e95bf5f14e
