### ISSUE TITLE
if(arr[idx] == val) adds the .ptr

### ISSUE THREAD

**Issue by schveiguy** [dkorpel/ctod#23]
```c
int buf[10];
if(buf[0] == 5) {}
```
```d
int[10] buf;
if(buf[0].ptr == 5) {}
```
That .ptr shouldn't be there.

**Comment by dkorpel** [comment]
It thought `buf` and `buf[0]` are the same expression because they have the same start location. Fixed by https://github.com/dkorpel/ctod/commit/2c23a7feeebad89daf9800993dfc957ddf2d938b
