### ISSUE TITLE
casts using custom types and parentheses don't turn into cast statements

### ISSUE THREAD

**Issue by schveiguy** [dkorpel/ctod#24]
```c
typedef unsigned char X;

void main()
{
   unsigned char c = 5;
   c = (unsigned char)(c + 5);

   c = (X)(c + 5);  
}
```

```d
alias X = ubyte;

int main() {
   ubyte c = 5;
   c = cast(ubyte)(c + 5);

   c = (X)(c + 5);  
}
```

That second line should change into a cast. It may not be as easily detectable. But there is a lot of code that uses typedefs, and casts.

Remove the parentheses around the expression, and it's recognized as a cast.

**Comment by dkorpel** [comment]
tree-sitter parses that as a function call. As of https://github.com/dkorpel/ctod/commit/86812e307261623e1c94b76c350a43363e35424a I rewrite function calls with parentheses to casts, since it's unlikely an actual regular function call would have redundant parentheses.

**Comment by dkorpel** [comment]
> it's unlikely an actual regular function call would have redundant parentheses

Considering you filed https://issues.dlang.org/show_bug.cgi?id=24025, this may not be true in your code. Can you comment on this?

**Comment by schveiguy** [comment]
> Can you comment on this?

Yep! I have both cases of course!

it appears like stb is a very good test of this translation tool.

Here is an instance of a cast to a typedef'd type:

https://github.com/schveiguy/draylib/blob/master/raylibc/external/stb_image.h#L1180

And in the same file, here is an instance of calling a function pointer for some reason by surrounding with parentheses (I think this is very uncommon):

https://github.com/schveiguy/draylib/blob/master/raylibc/external/stb_image.h#L1579

Now, as I mentioned in that bug report, I think not having the cast is fine for non-types, it shouldn't really trigger the error. But if I had to pick, I'd err on the side of using a cast, since there are many more cases of this syntax for casting than there are using it to... I guess clarify the intent of where the function pointer is? In either case, I get an error on the D side when it's wrong.

**Comment by dkorpel** [comment]
> And in the same file, here is an instance of calling a function pointer for some reason by surrounding with parentheses

Right, but that still has operators in the called expression:

```C
(s->io.read)(...);
```

ctod would only prepend `cast` if it were a single identifier:
```C
(read)(...);
```

So it should be good now

**Comment by schveiguy** [comment]
That works! Well, still have to remove the parentheses for now.

Thanks!
