### ISSUE TITLE
varargs calls would be nice to translate

### ISSUE THREAD

**Issue by schveiguy** [dkorpel/ctod#26]
with C, the macro `va_arg` does some funky stuff with a type name. You use it like:

```c
va_arg(v, int);
```
which comes out untouched on the D side, but obviously this is invalid syntax.

This should translate to:

```d
va_arg!int(v);
```

This translation isn't critical, I can do a search/replace, but it would be nice to have. Probably not a huge problem, as not many functions are actually varargs.

**Comment by dkorpel** [comment]
Partially fixed by https://github.com/dkorpel/ctod/commit/86812e307261623e1c94b76c350a43363e35424a

It works with single identifiers, but not things tree-sitter parses as an ERROR in that position, such as `unsigned int` or `int*`

**Comment by schveiguy** [comment]
Well, I have 3 cases, and all of them are `int`, so this should cover me.

This is such an unlikely feature that it's probably not worth getting that last 5% fixed ;)
