### ISSUE TITLE
static array parameters

### ISSUE THREAD

**Issue by schveiguy** [dkorpel/ctod#28]
If I have a function in C that takes a sized array, and a call with that same type, the translated D code will build, but won't be equivalent.

e.g.:

```c
#include <stdio.h>

void foo(unsigned short arr[2]) {
    arr[0] = 5;
}

int main() {
    // nested array needed to trick ctod into not putting a .ptr on it
    unsigned short arr[4][2] = { 0 };
    foo(arr[0]);
    printf("arr[0] is %d\n", arr[0][0]);
    return 0;
}
```

```d
module test;
@nogc nothrow:
extern(C): __gshared:
public import core.stdc.stdio;

void foo(ushort[2] arr) {
    arr[0] = 5;
}

int main() {
    // nested array needed to trick ctod into not putting a .ptr on it
    ushort[2][4] arr = 0;
    foo(arr[0]);
    printf("arr[0] is %d\n", arr[0][0]);
    return 0;
}
```

The C code prints `5`, the D code prints `0`

My recommendation is probably to use a pointer instead of the static array for the parameters. Or else, use `ref`. The former is more likely to compile with correct code without modification.

**Comment by schveiguy** [comment]
Well, it's not. But ctod is in the habit of changing static array arguments to `arr.ptr`.

Using ref is also a solution.

**Comment by dkorpel** [comment]
> But ctod is in the habit of changing static array arguments to `arr.ptr`.

That's a good point, with `ref`, I have to check the function parameter type before adding ".ptr", which I don't always know. I think I'll change it to a pointer so it can keep always adding `.ptr`.

**Comment by dkorpel** [comment]
Fixed by https://github.com/dkorpel/ctod/commit/850a44864cfb57b56db39d091b77f84b761cb849
