### ISSUE TITLE
non-initial float member of union shouldn't be default initialized to 0

### ISSUE THREAD

**Issue by schveiguy** [dkorpel/ctod#29]
In a struct, floats should be initialized to 0 to prevent surprises.

However, in a union, D does not permit setting the default value of members that aren't the first.

So the following doesn't work:

```c
typedef union
{
    stbir_uint32 u;
    float f;
} stbir__FP32;
```

```d
union _Stbir__FP32 {
    stbir_uint32 u;
    float f = 0; // error
}alias stbir__FP32 = _Stbir__FP32;
```

**Comment by dkorpel** [comment]
Fixed in https://github.com/dkorpel/ctod/commit/a517e4b83185defb1da73e18777153a86c811972 by adding scopes for types (I swear this thing is slowly becoming a complete compiler :laughing:  )
