### ISSUE TITLE
Sometimes structs aren't being copied

### ISSUE THREAD

**Issue by schveiguy** [dkorpel/ctod#3]
In a translated file, I have 

```c
struct sdefl_freq {
  unsigned lit[SDEFL_SYM_MAX];
  unsigned off[SDEFL_OFF_MAX];
};
struct sdefl_code_words {
  unsigned lit[SDEFL_SYM_MAX];
  unsigned off[SDEFL_OFF_MAX];
};
struct sdefl_lens {
  unsigned char lit[SDEFL_SYM_MAX];
  unsigned char off[SDEFL_OFF_MAX];
};
```

In the D file I get:

```d
sdefl_freq;
sdefl_code_words;
sdefl_lens;
```

Not sure why this is happening.

Reference file is: https://github.com/schveiguy/draylib/blob/0a7b3d1ada6ce4daedd95ed7fee0d34422b1782b/raylib/external/sdefl.h#L138

**Comment by dkorpel** [comment]
That's a pretty big regression introduced by https://github.com/dkorpel/ctod/commit/57a94a36b5258212219417ab8cbc5dc3a6ffd620 where it now translates the declaration as an inline type (as if the struct definition is inside a `cast()` or parameter list which D doesn't support). It doesn't help I tested manually while developing, and my little test suite is a bit of an afterthought :upside_down_face:

**Comment by dkorpel** [comment]
Fixed by https://github.com/dkorpel/ctod/commit/2322af0eba7d91c80705756a73972405e450bcf5
