### ISSUE TITLE
Let's talk about macros

### ISSUE THREAD

**Issue by schveiguy** [dkorpel/ctod#32]
I feel like the current macro translation situation is poor in ctod. Probably not ctod's fault, and again, we are creeping towards a full compiler but...

Just ran into this:

```c
#define MIN(a,b) (((a)<(b))?(a):(b))
pixels[y*image->width + x+1].r = MIN((int)pixels[y*image->width + x+1].r + (int)((float)rError*7.0f/16), 0xff);
```

Translates to: 

```d
enum string MIN(string a,string b) = ` (((a)<(b))?(a):(b))`;
pixels[y*image.width + x+1].r = MIN(cast(int)pixels[y*image.width + x+1].r + cast(int)(cast(float)rError*7.0f/16), 0xff);
```

Lots of problems here:

1. the enum doesn't actually do string substitution!
2. the call doesn't translate to using strings instead of the values themselves.
3. The call really should require a mixin!

I get that ctod has to do *something* here. But this isn't very useful. I get that understanding `MIN` is now a macro call, and therefore you change the expressions inside to strings would be difficult in an automatic way. But I'd almost rather have a nested function call than an enum here.

Can we explore other options?

**Comment by schveiguy** [comment]
For a start, I think the macro call should be translated as if it were actually a mixin:

```d
pixels[y*image.width + x+1].r = MIN!("cast(int)pixels[y*image.width + x+1].r + cast(int)(cast(float)rError*7.0f/16)", "0xff");
```

And really, the enum needs to be a true concatenation:
```d
enum string MIN(string a,string b) = `(((` ~ a ~ `)<(` ~ b ~ `))?(` ~ a ~ `):(` ~ b ~ `))`;
```

Does it need to be an enum? Maybe not, but then it just makes a new function to be linked...

**Comment by dkorpel** [comment]
It's now adding `mixin` to call macro functions, and concatenates the arguments properly. There's still a lot to improve, so please report any failure cases you encounter.
