### ISSUE TITLE
bad static array translation

### ISSUE THREAD

**Issue by schveiguy** [dkorpel/ctod#33]
```c
int foo[5]= {0,1,2,3,4};
int bar[5]= {1,2,3,4,5};
```
```d
int[5] foo = 0;
int[5] bar = [1,2,3,4,5];
```

The key is it has to be a static array, and the initializer values have to start with a 0.

This took me *forever* to figure out because I'm translating `stb_image` which is a giant nest of bit manipulation/lookup tables, and there are some static tables in the huffman decoding that started with 0! So basically, the huffman decoding was failing, and I couldn't figure out why.

Now that I have found this, I have it building and working ;)

**Comment by dkorpel** [comment]
Yikes! Sorry for that. Fixed by https://github.com/dkorpel/ctod/commit/46fbbf9dc702054824579c71fd751ef22e273b93

**Comment by schveiguy** [comment]
Thanks!
