### ISSUE TITLE
Integers 128bit support

### ISSUE THREAD

**Issue by kassane** [dkorpel/ctod#35]
### Why not 64-bit?

**A:** https://tigerbeetle.com/blog/2023-09-19-64-bit-bank-balances-ought-to-be-enough-for-anybody/

#### Source to translate:
https://github.com/tigerbeetle/tigerbeetle/blob/main/src/clients/c/tb_client.h

```c
#include <stdint.h>

typedef __uint128_t tb_uint128_t;
```
to:
```d
public import core.stdc.stdint; // why not core.int128 - Cent or std.int128 ?

alias tb_uint128_t = __uint128_t; // wrong!
```

**Similar reference**:
- https://github.com/jacob-carlborg/dstep/issues/288

**Comment by dkorpel** [comment]
Fixed by https://github.com/dkorpel/ctod/commit/4691c3b947b19536efe60aa91bf00fe2a389ea63
