### ISSUE TITLE
ctod doesn't understand sizeof expression

### ISSUE THREAD

**Issue by jibal** [dkorpel/ctod#41]
e.g., `sizeof foo.ptr` is passed through, when it should become `foo.ptr.sizeof`
And `sizeof x+y` should become `(x+y).sizeof`, etc.

**Comment by dkorpel** [comment]
Thanks, fixed in https://github.com/dkorpel/ctod/commit/aadfd3b64c33893f15fb40e80022c57d55ca9e03
