### ISSUE TITLE
Usage of struct tag results in odd translation

### ISSUE THREAD

**Issue by schveiguy** [dkorpel/ctod#5]
This is likely a somewhat uncommon occurrence as most code will typedef structs into a symbol, but using a struct with a tag as results in some odd code.

```c
struct S {
    int x;
};

struct T {
    struct S s;
};

void foo(struct T t);
```
```d
struct S {
    int x;
}

struct T {
    struct S ;S s;
}

struct T ;void foo(T t);
```

I have a file that uses structs without typedefs, and it doesn't translate well.

**Comment by dkorpel** [comment]
It does that because in C you can declare an opaque struct in-line:
```C
void f(struct S *s)
{

}
```
However, in your examples, it should deduce that there is no pointer type, so it has to be defined already and should not emit a type definition.

**Comment by schveiguy** [comment]
The example function don't match the actual code, where it *is* a pointer. But the struct *is* defined (possibly in another module), so redefining the struct is still wrong.

For sure, redefining the struct inside a nested struct is wrong.

However, this is D. Can you not record which structs may or may not have been defined, and just spit out some `struct S` at the end if you hadn't seen it yet?

**Comment by dkorpel** [comment]
Fixed by https://github.com/dkorpel/ctod/commit/7cd36c10b72c60765eff95a742d0f8de379d8bea

I now assume that bodyless enum/struct types are already defined, even when they have pointer types.

**Comment by schveiguy** [comment]
Just tested by compiling, and it does indeed complain if you redefine the struct within the same module, even to just define as a prototype.

**Comment by dkorpel** [comment]
I suppose a future enhancement would be to manage a symbol table to know which symbols have been defined already, but unless you also read all `#include`s you still cannot be sure.

**Comment by schveiguy** [comment]
Yeah, it's probably not a huge deal, because defining the struct in the module is such a different thing than defining it again in C.
