### ISSUE TITLE
Nice to have: initialization of static arrays of builtin types

### ISSUE THREAD

**Issue by schveiguy** [dkorpel/ctod#8]
C:
```c
int x[10] = {0};
```
D:
```d
int[10] x = [0];
```

Results in a compiler error for size mismatch. Nicer would be:

```d
int[10] x = 0;
```

This won't work in all situations, but the current behavior will never work.

**Comment by dkorpel** [comment]
> Results in a compiler error for size mismatch. 

Only in function scope apparently:
```D

void main()
{
	int[10] x = [0]; // error
}

int[10] x = [0]; // no error?
```
Kinda surprised.

But indeed, initializer translation needs work. In C, `{0}` can initialize almost anything. D is a lot more specific and picky with initializers.

**Comment by schveiguy** [comment]
> Only in function scope apparently

Huh, that's odd.

But I was actually thinking -- would it be possible to write an `allZeros!T` template that properly initializes any type? That could be used in its place. It might not be easy to do with CTFE.

Normally when translating, I have just been removing the initializer and using auto initialization. The one place where it is a problem is floating point types or char buffers.

**Comment by dkorpel** [comment]
Fixed by recognizing {} and {0} on static arrays in https://github.com/dkorpel/ctod/commit/0f31729fe2d7bc5594796eff7d0b47a9db957f09

> Normally when translating, I have just been removing the initializer and using auto initialization. The one place where it is a problem is floating point types or char buffers.

I'm thinking that `char`/`float` members of structs should add a `= 0;` on the D side so `S.init` can be used.
