### ISSUE TITLE
adding integer to C array

### ISSUE THREAD

**Issue by schveiguy** [dkorpel/ctod#9]
C:
```c
void foo(void) {
    int x[10];
    int *ptr = x + 5;
}
```
D:
```d
void foo() {
    int[10] x;
    int* ptr = x + 5; // should be x.ptr + 5
}
```
Not sure if this is solvable in the general case, but you seem to be able to sniff out pointer usage in other cases when it's a static array.

**Comment by schveiguy** [comment]
I'm wondering if in general usage of a static array except when indexing should just always tack on `.ptr`.

**Comment by schveiguy** [comment]
Hm... this might require some semantic analysis, which is probably not going to happen.

**Comment by dkorpel** [comment]
> Not sure if this is solvable in the general case, but you seem to be able to sniff out pointer usage in other cases when it's a static array.

Indeed, I'm already keeping symbol tables with types, and if you pass an identifier in a call expression and it has seen that identifier declared as a static array, it adds ".ptr". I can do the same for binary expressions.

**Comment by dkorpel** [comment]
Fixed by https://github.com/dkorpel/ctod/commit/d0ebea8395d48acf370797f54b7e81b3ac124ce3

It doesn't type check struct field access yet, and there's probably bugs, but in the most common cases it should add `.ptr`.
